# Generated by Django 3.1.2 on 2020-11-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id_agendamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, null=True)),
                ('telefone', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('queixa', models.CharField(max_length=1000, null=True)),
                ('pedido_medico', models.FileField(default='', upload_to='', verbose_name='Pedido Médico')),
                ('data_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'agenda',
            },
        ),
    ]
