# Generated by Django 3.1.2 on 2020-11-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='pedido_medico',
            field=models.CharField(max_length=1000, null=True, verbose_name='Pedido Médico'),
        ),
    ]
