# Generated by Django 3.1.2 on 2020-11-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_agenda_pedido_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='pedido_medico',
            field=models.FileField(default='', upload_to='', verbose_name='Pedido Médico'),
        ),
    ]
