# Generated by Django 3.1.2 on 2020-11-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id_supervisor', models.AutoField(primary_key=True, serialize=False)),
                ('nome_supervisor', models.CharField(max_length=100, null=True)),
                ('telefone_supervisor', models.CharField(max_length=100, null=True)),
                ('crefito', models.CharField(max_length=10, null=True, verbose_name='CREFITO')),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('EXCLUIDO', 'EXCLUIDO')], default='ATIVO', max_length=10, null=True, verbose_name='Status')),
                ('data_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'supervisor',
            },
        ),
    ]
