# Generated by Django 3.1.2 on 2020-10-25 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profissional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_paciente', models.CharField(max_length=100, null=True)),
                ('telefone_paciente', models.CharField(max_length=100, null=True)),
                ('estado_civil', models.CharField(choices=[('SOLTEIRO', 'SOLTEIRO'), ('CASADO', 'CASADO'), ('UNIAO ESTAVEL', 'UNIAO ESTAVEL'), ('DIVORCIADO', 'DIVORCIADO'), ('SEPARADO', 'SEPARADO'), ('OUTROS', 'OUTROS')], max_length=15)),
                ('naturalidade', models.CharField(max_length=100, null=True)),
                ('genero', models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMININO', 'FEMININO'), ('OUTROS', 'OUTROS')], max_length=15)),
                ('local_nascimento', models.CharField(max_length=100, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('profissao', models.CharField(max_length=100, null=True)),
                ('endereco_comercial', models.CharField(max_length=100, null=True)),
                ('endereco_residencial', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('EXCLUIDO', 'EXCLUIDO')], default='ATIVO', max_length=10, null=True, verbose_name='Status')),
                ('data_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True, null=True)),
                ('profissional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profissional.profissional')),
            ],
            options={
                'db_table': 'pacientes',
            },
        ),
    ]
