# Generated by Django 3.1.2 on 2020-11-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_paciente', models.CharField(max_length=100, null=True)),
                ('telefone_paciente', models.CharField(max_length=100, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('SOLTEIRO', 'SOLTEIRO'), ('CASADO', 'CASADO'), ('UNIAO ESTAVEL', 'UNIAO ESTAVEL'), ('DIVORCIADO', 'DIVORCIADO'), ('SEPARADO', 'SEPARADO'), ('OUTROS', 'OUTROS')], max_length=15)),
                ('nacionalidade', models.CharField(max_length=100, null=True)),
                ('genero', models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMININO', 'FEMININO'), ('OUTROS', 'OUTROS')], max_length=15)),
                ('cidade', models.CharField(max_length=100, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('profissao', models.CharField(blank=True, max_length=100)),
                ('endereco_comercial', models.CharField(blank=True, max_length=100)),
                ('endereco_residencial', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('nome_acompanhante', models.CharField(blank=True, max_length=100)),
                ('diag_clinico', models.CharField(max_length=1000, null=True, verbose_name='Diagnóstico Clínico')),
                ('ch_faixa_etaria', models.CharField(choices=[('ADULTO', 'ADULTO'), ('ADOLESCENTE', 'ADOLESCENTE'), ('CRIANÇA', 'CRIANÇA')], default='', max_length=11, null=True, verbose_name='Faixa Etária')),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('EXCLUIDO', 'EXCLUIDO')], default='ATIVO', max_length=10, null=True, verbose_name='Status')),
                ('data_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'pacientes',
            },
        ),
    ]
