# Generated by Django 3.1.2 on 2020-10-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nm_paciente', models.CharField(max_length=100, null=True)),
                ('nu_telefone_paciente', models.CharField(max_length=100, null=True)),
                ('nm_naturalidade', models.CharField(max_length=100, null=True)),
                ('de_estado_civil', models.CharField(max_length=100, null=True)),
                ('de_genero', models.CharField(max_length=100, null=True)),
                ('de_local_nascimento', models.CharField(max_length=100, null=True)),
                ('dt_nascimento', models.DateTimeField(blank=True, null=True)),
                ('de_profissao', models.CharField(max_length=100, null=True)),
                ('de_endereco_comercial', models.CharField(max_length=100, null=True)),
                ('de_endereco_residencial', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('EXCLUIDO', 'EXCLUIDO')], default='ATIVO', max_length=10, null=True, verbose_name='Status')),
                ('data_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'pacientes',
            },
        ),
    ]
