# Generated by Django 3.1.2 on 2020-11-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='local_nascimento',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='pacientes',
            old_name='naturalidade',
            new_name='nacionalidade',
        ),
        migrations.AddField(
            model_name='pacientes',
            name='ch_faixa_etaria',
            field=models.CharField(choices=[('ADULTO', 'ADULTO'), ('ADOLESCENTE', 'ADOLESCENTE'), ('CRIANÇA', 'CRIANÇA')], default='', max_length=11, null=True, verbose_name='Faixa Etária'),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='diag_clinico',
            field=models.CharField(max_length=1000, null=True, verbose_name='Diagnóstico Clínico'),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='nome_acompanhante',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
