# Generated by Django 3.1.2 on 2020-10-24 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profissional', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profissional.profissional'),
        ),
    ]
