# Generated by Django 3.1.2 on 2020-10-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_pacientes_profissional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='dt_nascimento',
            new_name='data_nascimento',
        ),
        migrations.RenameField(
            model_name='pacientes',
            old_name='de_endereco_comercial',
            new_name='endereco_comercial',
        ),
        migrations.RenameField(
            model_name='pacientes',
            old_name='de_endereco_residencial',
            new_name='endereco_residencial',
        ),
        migrations.RenameField(
            model_name='pacientes',
            old_name='de_estado_civil',
            new_name='estado_civil',
        ),
        migrations.RenameField(
            model_name='pacientes',
            old_name='de_genero',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='pacientes',
            old_name='de_local_nascimento',
            new_name='local_nascimento',
        ),
        migrations.RenameField(
            model_name='pacientes',
            old_name='de_profissao',
            new_name='naturalidade',
        ),
        migrations.RenameField(
            model_name='pacientes',
            old_name='nm_naturalidade',
            new_name='nome_paciente',
        ),
        migrations.RenameField(
            model_name='pacientes',
            old_name='nm_paciente',
            new_name='profissao',
        ),
        migrations.RenameField(
            model_name='pacientes',
            old_name='nu_telefone_paciente',
            new_name='telefone_paciente',
        ),
    ]
