# Generated by Django 3.1.2 on 2020-10-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_auto_20201024_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
