# Generated by Django 3.1.2 on 2020-11-16 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('profissional', '0001_initial'),
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id_anamnese', models.AutoField(primary_key=True, serialize=False)),
                ('historia_clinica', models.CharField(max_length=1000, null=True)),
                ('exame_clinico_funcional', models.CharField(max_length=1000, null=True)),
                ('exames_complementares', models.CharField(max_length=1000, null=True)),
                ('diagnostico', models.CharField(max_length=1000, null=True)),
                ('plano_terapeutico', models.CharField(max_length=1000, null=True)),
                ('evolucao', models.CharField(max_length=1000, null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('EXCLUIDO', 'EXCLUIDO')], default='ATIVO', max_length=10, null=True, verbose_name='Status')),
                ('alunoa', models.CharField(max_length=100, null=True, verbose_name='Aluno A')),
                ('alunob', models.CharField(blank=True, max_length=100, verbose_name='Aluno B')),
                ('alunoc', models.CharField(blank=True, max_length=100, verbose_name='Aluno C')),
                ('alunod', models.CharField(blank=True, max_length=100, verbose_name='Aluno D')),
                ('data_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pacientes.pacientes')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profissional.professor')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supervisor.supervisor')),
            ],
            options={
                'db_table': 'anamnese',
            },
        ),
    ]
