# Generated by Django 3.1.2 on 2020-10-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id_anamnese', models.AutoField(primary_key=True, serialize=False)),
                ('de_historia_clinica', models.CharField(max_length=1000, null=True)),
                ('de_exame_clinico_funcional', models.CharField(max_length=1000, null=True)),
                ('de_exames_complementares', models.CharField(max_length=1000, null=True)),
                ('de_diagnostico', models.CharField(max_length=1000, null=True)),
                ('de_plano_terapeutico', models.CharField(max_length=1000, null=True)),
                ('de_evolucao', models.CharField(max_length=1000, null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('EXCLUIDO', 'EXCLUIDO')], default='ATIVO', max_length=10, null=True, verbose_name='Status')),
                ('data_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'anamnese',
            },
        ),
    ]
