# Generated by Django 3.1.2 on 2020-11-11 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0001_initial'),
        ('supervisor', '0001_initial'),
        ('anamnese', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='alunoa',
            field=models.CharField(max_length=100, null=True, verbose_name='Aluno A'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='alunob',
            field=models.CharField(max_length=100, null=True, verbose_name='Aluno B'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='alunoc',
            field=models.CharField(max_length=100, null=True, verbose_name='Aluno C'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='alunod',
            field=models.CharField(max_length=100, null=True, verbose_name='Aluno D'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='profissional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profissional.profissional'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supervisor.supervisor'),
        ),
    ]
