# Generated by Django 3.1.2 on 2020-10-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0003_anamnese_profissional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anamnese',
            old_name='de_diagnostico',
            new_name='diagnostico',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='de_evolucao',
            new_name='evolucao',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='de_exame_clinico_funcional',
            new_name='exame_clinico_funcional',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='de_exames_complementares',
            new_name='exames_complementares',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='de_historia_clinica',
            new_name='historia_clinica',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='de_plano_terapeutico',
            new_name='plano_terapeutico',
        ),
    ]
