# Generated by Django 3.1.2 on 2020-11-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='crefito',
            field=models.CharField(max_length=10, null=True, verbose_name='CREFITO'),
        ),
    ]
