# Generated by Django 3.1.2 on 2020-10-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissional',
            old_name='nm_profissional',
            new_name='nome_profissional',
        ),
        migrations.RenameField(
            model_name='profissional',
            old_name='nu_telefone_profissional',
            new_name='telefone_profissional',
        ),
        migrations.RenameField(
            model_name='profissional',
            old_name='usuarios',
            new_name='usuario',
        ),
    ]
