# Generated by Django 3.1.2 on 2020-11-16 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profissional',
            table='Professor',
        ),
    ]
