# Generated by Django 3.1.2 on 2020-11-16 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0002_auto_20201116_1939'),
        ('usuarios', '0001_initial'),
        ('anamnese', '0002_auto_20201116_1939'),
        ('profissional', '0002_auto_20201116_1934'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profissional',
            new_name='Professor',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='id_profissional',
            new_name='id_professor',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='nome_profissional',
            new_name='nome_professor',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='telefone_profissional',
            new_name='telefone_professor',
        ),
    ]
