# Generated by Django 3.1.2 on 2020-11-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='diag_clinico',
            field=models.CharField(max_length=1000, null=True, verbose_name='Diagnóstico Clínico'),
        ),
    ]
