# Generated by Django 3.1.2 on 2020-11-11 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('profissional', '0001_initial'),
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id_avaliacao_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('avaliacao_upload', models.CharField(max_length=1000, null=True, verbose_name='Uoload da Avaliação')),
                ('observacoes', models.CharField(max_length=1000, verbose_name='Observações')),
                ('ciclo', models.CharField(max_length=1000, null=True)),
                ('alunoa', models.CharField(max_length=100, verbose_name='Aluno A')),
                ('alunob', models.CharField(max_length=100, verbose_name='Aluno B')),
                ('alunoc', models.CharField(max_length=100, verbose_name='Aluno C')),
                ('alunod', models.CharField(max_length=100, verbose_name='Aluno D')),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('EXCLUIDO', 'EXCLUIDO')], default='ATIVO', max_length=10, null=True, verbose_name='Status')),
                ('data_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pacientes.pacientes')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profissional.profissional')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supervisor.supervisor')),
            ],
            options={
                'db_table': 'avaliacao',
            },
        ),
    ]
