# Generated by Django 3.1.2 on 2020-10-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id_avaliacao_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('nm_aluno', models.CharField(max_length=100, null=True)),
                ('de_avaliacao', models.CharField(max_length=1000, null=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('EXCLUIDO', 'EXCLUIDO')], default='ATIVO', max_length=10, null=True, verbose_name='Status')),
                ('data_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'avaliacao',
            },
        ),
    ]
