# Generated by Django 3.1.2 on 2020-11-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='alunoa',
            field=models.CharField(max_length=100, null=True, verbose_name='Aluno A'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='alunob',
            field=models.CharField(max_length=100, null=True, verbose_name='Aluno B'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='alunoc',
            field=models.CharField(max_length=100, null=True, verbose_name='Aluno C'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='alunod',
            field=models.CharField(max_length=100, null=True, verbose_name='Aluno D'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='avaliacao_upload',
            field=models.CharField(max_length=1000, null=True, verbose_name='Upload da Avaliação'),
        ),
    ]
