# Generated by Django 3.1.2 on 2020-11-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='area',
            field=models.CharField(max_length=100, null=True, verbose_name='Área de Intervenção'),
        ),
    ]
