# Generated by Django 3.1.2 on 2020-11-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0002_auto_20201110_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='avaliacao_upload',
            field=models.FileField(default='', upload_to='', verbose_name='Upload da Avaliação'),
        ),
    ]
