# Generated by Django 3.1.2 on 2020-10-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0002_avaliacao_profissional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='de_avaliacao',
            new_name='avaliacao',
        ),
        migrations.RenameField(
            model_name='avaliacao',
            old_name='nm_aluno',
            new_name='nome_aluno',
        ),
    ]
